import type { AvatarProject } from '../types/avatar'
import { buildAvatar, serializeNode } from './render'
import { avatarStylesheet } from './animationCss'
import { allExpressionNames, expressionLabel, getExpressionDef, isCustomExpression } from './customExpressions'

export function componentName(project: AvatarProject): string {
  const cleaned = project.name.replace(/[^a-zA-Z0-9 _-]/g, '').trim() || 'MyAvatar'
  const pascal = cleaned
    .split(/[\s_-]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('')
  return /^[A-Za-z]/.test(pascal) ? pascal : `Avatar${pascal}`
}

export function includedExpressions(project: AvatarProject): string[] {
  const names = allExpressionNames(project).filter((n) => project.expressions[n]?.include)
  if (!names.includes('idle')) names.unshift('idle')
  return names
}

function indentBlock(text: string, indent: string): string {
  return text
    .split('\n')
    .map((line) => (line.trim() ? indent + line : line))
    .join('\n')
}

/** The single-file .vue component. Zero runtime dependencies. */
export function generateComponent(project: AvatarProject): string {
  const name = componentName(project)
  const expressions = includedExpressions(project)
  // Only embed props for expressions that actually ship.
  const render = buildAvatar(project, 'avatar', expressions)
  const playOnce = expressions.filter((n) => {
    const loop = project.expressions[n]?.loop
    return loop === 'once' || typeof loop === 'number'
  })

  const svgChildren = render.nodes.map((n) => serializeNode(n, '    ')).join('\n')
  const css = avatarStylesheet(project, '.avatar', 'avatar', expressions)

  // Custom expressions ship under their CSS-safe slug; note the display names.
  const customNotes = expressions
    .filter((n) => isCustomExpression(n))
    .map((n) => {
      const def = getExpressionDef(project, n)
      return def && expressionLabel(def) !== n ? `// Custom expression "${expressionLabel(def)}" plays as expression="${n}".` : ''
    })
    .filter(Boolean)
    .join('\n')

  return `<script setup>
// ${name}.vue — generated by Avatar Builder. No runtime dependencies.
${customNotes ? customNotes + '\n' : ''}
import { computed, ref, watch } from 'vue'

const props = defineProps({
  /** One of: ${expressions.join(', ')} */
  expression: {
    type: String,
    default: 'idle',
    validator: (value) => ${JSON.stringify(expressions)}.includes(value),
  },
  /** Rendered width — a number of pixels or any CSS size. */
  size: {
    type: [Number, String],
    default: 200,
  },
  paused: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits(['animation-end'])

const cssSize = computed(() => (typeof props.size === 'number' ? \`\${props.size}px\` : props.size))

const hasEmittedEnd = ref(false)
watch(() => props.expression, () => {
  hasEmittedEnd.value = false
})

function onAnimationEnd(event) {
  // Several tracks finish together; report the expression once per play.
  if (hasEmittedEnd.value) return
  if (!event.animationName.includes(\`avatar-\${props.expression}-\`)) return
  hasEmittedEnd.value = true
  emit('animation-end', props.expression)
}
</script>

<template>
  <svg
    class="avatar"
    :class="\`avatar-expr--\${expression}\`"
    :style="{ width: cssSize, '--avatar-play': paused ? 'paused' : 'running' }"
    viewBox="${render.viewBox}"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="${name} avatar"
    @animationend="onAnimationEnd"
  >
${svgChildren}
  </svg>
</template>

<style scoped>
.avatar {
  height: auto;
  display: block;
  overflow: visible;
}

${css}
</style>
${playOnce.length ? `\n<!-- Play-once expressions (${playOnce.join(', ')}) emit "animation-end" when they finish. -->\n` : ''}`
}

/** Optional bundle: expression config as a typed module. */
export function generateExpressionsTs(project: AvatarProject): string {
  const expressions = includedExpressions(project)
  const entries = expressions.map((n) => {
    const s = project.expressions[n]
    const def = getExpressionDef(project, n)!
    const key = /^[a-z_$][\w$]*$/i.test(n) ? n : JSON.stringify(n)
    return `  ${key}: { duration: ${(def.duration / s.speed).toFixed(2)}, speed: ${s.speed}, intensity: ${s.intensity}, loop: ${JSON.stringify(s.loop)} },`
  })
  return `// Expression configuration for ${componentName(project)}.vue — generated by Avatar Builder.

export const expressions = {
${entries.join('\n')}
} as const

export type ExpressionName = keyof typeof expressions
`
}

export function generateReadme(project: AvatarProject): string {
  const name = componentName(project)
  const expressions = includedExpressions(project)
  return `# ${name}

An animated avatar component generated by Avatar Builder. Plain Vue 3, no dependencies.

## Usage

\`\`\`vue
<script setup>
import ${name} from './${name}.vue'
</script>

<template>
  <${name} expression="happy" :size="240" />
</template>
\`\`\`

## Props

| Prop | Type | Default | Notes |
| --- | --- | --- | --- |
| \`expression\` | \`string\` | \`"idle"\` | One of: ${expressions.map((e) => `\`${e}\``).join(', ')} |
| \`size\` | \`number \\| string\` | \`200\` | Pixel width, or any CSS size (e.g. \`"12rem"\`) |
| \`paused\` | \`boolean\` | \`false\` | Freezes all animation |

## Events

- \`animation-end\` — fired when a play-once expression finishes (payload: the expression name).

The idle blink runs in every expression. Switching \`expression\` cross-fades the mouth shape smoothly.
`
}

/** Static SVG snapshot of the current pose (no animation). */
export function generateSvgSnapshot(project: AvatarProject): string {
  // No expression props in a static snapshot — they only exist mid-animation.
  const render = buildAvatar(project, 'snap', [])
  const children = render.nodes.map((n) => serializeNode(n, '  ')).join('\n')
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${render.viewBox}" width="${Math.round(render.width * 2)}" height="${Math.round(render.height * 2)}">\n${children}\n</svg>\n`
}
