import type { AvatarProject } from '../types/avatar'
import type { SvgNode } from './render'
import { buildAvatar } from './render'
import { avatarStylesheet } from './animationCss'
import { expressionLabel, getExpressionDef, isCustomExpression } from './customExpressions'
import { componentName, includedExpressions } from './exporter'

const VOID_OK = new Set(['stop', 'circle', 'path', 'rect', 'ellipse', 'line'])

/** SVG attribute names JSX spells differently. Everything else is kebab -> camel. */
function jsxAttrName(name: string): string {
  if (name === 'class') return 'className'
  if (name.startsWith('data-') || name.startsWith('aria-')) return name
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

/** The string-serialiser from render.ts, emitting JSX attributes instead of SVG ones. */
export function serializeNodeJsx(node: SvgNode, indent = ''): string {
  const attrs = Object.entries(node.attrs)
    .map(([k, v]) => (typeof v === 'number' ? ` ${jsxAttrName(k)}={${v}}` : ` ${jsxAttrName(k)}="${v}"`))
    .join('')
  const children = node.children ?? []
  if (children.length === 0 && VOID_OK.has(node.tag)) {
    return `${indent}<${node.tag}${attrs} />`
  }
  if (children.length === 0) return `${indent}<${node.tag}${attrs}></${node.tag}>`
  const inner = children.map((c) => serializeNodeJsx(c, indent + '  ')).join('\n')
  return `${indent}<${node.tag}${attrs}>\n${inner}\n${indent}</${node.tag}>`
}

/** The stylesheet is carried in a template literal, so neutralise its delimiters. */
function escapeTemplate(css: string): string {
  return css.replace(/[`\\]/g, '\\$&').replace(/\$\{/g, '\\${')
}

/** The single-file .tsx component. Zero runtime dependencies beyond React. */
export function generateReactComponent(project: AvatarProject): string {
  const name = componentName(project)
  const expressions = includedExpressions(project)
  // Only embed props for expressions that actually ship.
  const render = buildAvatar(project, 'avatar', expressions)
  const playOnce = expressions.filter((n) => {
    const loop = project.expressions[n]?.loop
    return loop === 'once' || typeof loop === 'number'
  })

  const svgChildren = render.nodes.map((n) => serializeNodeJsx(n, '      ')).join('\n')
  const css = `.avatar {
  height: auto;
  display: block;
  overflow: visible;
}

${avatarStylesheet(project, '.avatar', 'avatar', expressions)}`

  // Custom expressions ship under their CSS-safe slug; note the display names.
  const customNotes = expressions
    .filter((n) => isCustomExpression(n))
    .map((n) => {
      const def = getExpressionDef(project, n)
      return def && expressionLabel(def) !== n ? `// Custom expression "${expressionLabel(def)}" plays as expression="${n}".` : ''
    })
    .filter(Boolean)
    .join('\n')

  return `// ${name}.tsx — generated by Avatar Builder. No runtime dependencies.
${customNotes ? customNotes + '\n' : ''}${playOnce.length ? `// Play-once expressions (${playOnce.join(', ')}) call onAnimationEnd when they finish.\n` : ''}import { useEffect, useRef, type AnimationEvent, type CSSProperties } from 'react'

export type ExpressionName = ${expressions.map((e) => `'${e}'`).join(' | ')}

export interface ${name}Props {
  expression?: ExpressionName
  /** Rendered width — a number of pixels or any CSS size. */
  size?: number | string
  paused?: boolean
  onAnimationEnd?: (expression: ExpressionName) => void
}

const CSS = \`${escapeTemplate(css)}\`

export default function ${name}({ expression = 'idle', size = 200, paused = false, onAnimationEnd }: ${name}Props) {
  const hasEmittedEnd = useRef(false)
  useEffect(() => {
    hasEmittedEnd.current = false
  }, [expression])

  function handleAnimationEnd(event: AnimationEvent) {
    // Several tracks finish together; report the expression once per play.
    if (hasEmittedEnd.current) return
    if (!event.animationName.includes(\`avatar-\${expression}-\`)) return
    hasEmittedEnd.current = true
    onAnimationEnd?.(expression)
  }

  return (
    <svg
      className={\`avatar avatar-expr--\${expression}\`}
      style={
        {
          width: typeof size === 'number' ? \`\${size}px\` : size,
          '--avatar-play': paused ? 'paused' : 'running',
        } as CSSProperties
      }
      viewBox="${render.viewBox}"
      xmlns="http://www.w3.org/2000/svg"
      role="img"
      aria-label="${name} avatar"
      onAnimationEnd={handleAnimationEnd}
    >
      <style>{CSS}</style>
${svgChildren}
    </svg>
  )
}
`
}

export function generateReactReadme(project: AvatarProject): string {
  const name = componentName(project)
  const expressions = includedExpressions(project)
  return `# ${name}

An animated avatar component generated by Avatar Builder. Plain React, no dependencies.

## Usage

\`\`\`tsx
import ${name} from './${name}'

export function Example() {
  return <${name} expression="happy" size={240} />
}
\`\`\`

## Props

| Prop | Type | Default | Notes |
| --- | --- | --- | --- |
| \`expression\` | \`ExpressionName\` | \`"idle"\` | One of: ${expressions.map((e) => `\`${e}\``).join(', ')} |
| \`size\` | \`number \\| string\` | \`200\` | Pixel width, or any CSS size (e.g. \`"12rem"\`) |
| \`paused\` | \`boolean\` | \`false\` | Freezes all animation |
| \`onAnimationEnd\` | \`(expression: ExpressionName) => void\` | — | Called once when a play-once expression finishes |

The idle blink runs in every expression. Switching \`expression\` cross-fades the mouth shape smoothly.
`
}
