<script setup>
// BoxBuddy.vue — generated by Avatar Builder. No runtime dependencies.
import { computed, ref, watch } from 'vue'

const props = defineProps({
  /** One of: idle, happy, curious, surprised, sleepy, wink */
  expression: {
    type: String,
    default: 'idle',
    validator: (value) => ["idle","happy","curious","surprised","sleepy","wink"].includes(value),
  },
  /** Rendered width — a number of pixels or any CSS size. */
  size: {
    type: [Number, String],
    default: 200,
  },
  paused: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits(['animation-end'])

const cssSize = computed(() => (typeof props.size === 'number' ? `${props.size}px` : props.size))

const hasEmittedEnd = ref(false)
watch(() => props.expression, () => {
  hasEmittedEnd.value = false
})

function onAnimationEnd(event) {
  // Several tracks finish together; report the expression once per play.
  if (hasEmittedEnd.value) return
  if (!event.animationName.includes(`avatar-${props.expression}-`)) return
  hasEmittedEnd.value = true
  emit('animation-end', props.expression)
}
</script>

<template>
  <svg
    class="avatar"
    :class="`avatar-expr--${expression}`"
    :style="{ width: cssSize, '--avatar-play': paused ? 'paused' : 'running' }"
    viewBox="-114.3 -176.3 228.5 280.3"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="BoxBuddy avatar"
    @animationend="onAnimationEnd"
  >
    <defs>
      <linearGradient id="avatar-body-grad" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stop-color="#d9a066" />
        <stop offset="100%" stop-color="#b28354" />
      </linearGradient>
      <clipPath id="avatar-eye-clip">
        <path d="M -16 0 a 16 16 0 1 0 32 0 a 16 16 0 1 0 -32 0 Z" />
      </clipPath>
    </defs>
    <g class="avatar-root">
      <g class="avatar-squash">
        <g class="avatar-body">
          <path d="M -66 -80 h 132 a 24 24 0 0 1 24 24 v 112 a 24 24 0 0 1 -24 24 h -132 a 24 24 0 0 1 -24 -24 v -112 a 24 24 0 0 1 24 -24 Z" fill="url(#avatar-body-grad)" />
        </g>
        <g class="avatar-part" data-part-id="tape" transform="translate(0 -62)">
          <path d="M -88 -7 h 176 a 2 2 0 0 1 2 2 v 10 a 2 2 0 0 1 -2 2 h -176 a 2 2 0 0 1 -2 -2 v -10 a 2 2 0 0 1 2 -2 Z" fill="#c98d52" />
        </g>
        <g class="avatar-part" data-part-id="label" transform="translate(52 52) rotate(-6)">
          <path d="M -18 -14 h 36 a 4 4 0 0 1 4 4 v 20 a 4 4 0 0 1 -4 4 h -36 a 4 4 0 0 1 -4 -4 v -20 a 4 4 0 0 1 4 -4 Z" fill="#f2e6d4" stroke="#b07d4a" stroke-width="2" />
        </g>
        <g class="avatar-part" data-part-id="blush" transform="translate(-52 8)">
          <path d="M -11 0 a 11 6 0 1 0 22 0 a 11 6 0 1 0 -22 0 Z" fill="#e8917c" opacity="0.65" />
        </g>
        <g class="avatar-part" data-part-id="blush--mirror" transform="translate(52 8) scale(-1 1)">
          <path d="M -11 0 a 11 6 0 1 0 22 0 a 11 6 0 1 0 -22 0 Z" fill="#e8917c" opacity="0.65" />
        </g>
        <g class="avatar-face">
          <g class="avatar-eye avatar-eye--left" transform="translate(-38 -18)">
            <g class="avatar-eye-anim">
              <g class="avatar-eye-open">
                <g class="avatar-eye-blink">
                  <g transform="scale(1 1)">
                    <path d="M -16 0 a 16 16 0 1 0 32 0 a 16 16 0 1 0 -32 0 Z" fill="#ffffff" />
                    <g clip-path="url(#avatar-eye-clip)">
                      <g class="avatar-pupil-anim">
                        <g class="avatar-pupil">
                          <circle r="8" fill="#2b2b2b" />
                          <circle r="2.24" cx="-2.56" cy="-3.2" fill="#ffffff" />
                        </g>
                      </g>
                    </g>
                  </g>
                </g>
              </g>
              <path class="avatar-eye-closed" d="M -13.76 0 Q 0 2.88 13.76 0" fill="none" stroke="#2b2b2b" stroke-width="2.4" stroke-linecap="round" opacity="0" />
              <path class="avatar-eye-smile" d="M -13.76 1.92 Q 0 -6.72 13.76 1.92" fill="none" stroke="#2b2b2b" stroke-width="2.4" stroke-linecap="round" opacity="0" />
              <path class="avatar-eyebrow" d="M -15.2 -21.6 Q 0 -25.92 15.2 -21.6" fill="none" stroke="#2b2b2b" stroke-width="3.84" stroke-linecap="round" opacity="0" />
            </g>
          </g>
          <g class="avatar-eye avatar-eye--right" transform="translate(38 -18)">
            <g class="avatar-eye-anim">
              <g class="avatar-eye-open">
                <g class="avatar-eye-blink">
                  <g transform="scale(1 1)">
                    <path d="M -16 0 a 16 16 0 1 0 32 0 a 16 16 0 1 0 -32 0 Z" fill="#ffffff" />
                    <g clip-path="url(#avatar-eye-clip)">
                      <g class="avatar-pupil-anim">
                        <g class="avatar-pupil">
                          <circle r="8" fill="#2b2b2b" />
                          <circle r="2.24" cx="-2.56" cy="-3.2" fill="#ffffff" />
                        </g>
                      </g>
                    </g>
                  </g>
                </g>
              </g>
              <path class="avatar-eye-closed" d="M -13.76 0 Q 0 2.88 13.76 0" fill="none" stroke="#2b2b2b" stroke-width="2.4" stroke-linecap="round" opacity="0" />
              <path class="avatar-eye-smile" d="M -13.76 1.92 Q 0 -6.72 13.76 1.92" fill="none" stroke="#2b2b2b" stroke-width="2.4" stroke-linecap="round" opacity="0" />
              <path class="avatar-eyebrow" d="M -15.2 -21.6 Q 0 -25.92 15.2 -21.6" fill="none" stroke="#2b2b2b" stroke-width="3.84" stroke-linecap="round" opacity="0" />
            </g>
          </g>
          <g class="avatar-mouth-wrap" transform="translate(0 28)">
            <g class="avatar-mouth-anim">
              <path class="avatar-mouth" d="M -22 0 Q 0 14 22 0" fill="none" stroke="#2b2b2b" stroke-width="3.5" stroke-linecap="round" />
            </g>
          </g>
        </g>
        <g class="avatar-props">
          <g transform="translate(-85.5 -60.0)">
            <g class="avatar-prop avatar-prop--surprised-spark1" opacity="0">
              <path d="M 0 -11.200000000000001 Q 2.016 -2.016 11.200000000000001 0 Q 2.016 2.016 0 11.200000000000001 Q -2.016 2.016 -11.200000000000001 0 Q -2.016 -2.016 0 -11.200000000000001 Z" fill="#f6c344" />
            </g>
          </g>
          <g transform="translate(76.5 -84.0)">
            <g class="avatar-prop avatar-prop--surprised-spark2" opacity="0">
              <path d="M 0 -8.8 Q 1.584 -1.584 8.8 0 Q 1.584 1.584 0 8.8 Q -1.584 1.584 -8.8 0 Q -1.584 -1.584 0 -8.8 Z" fill="#f6c344" />
            </g>
          </g>
          <g transform="translate(-27.0 -108.0)">
            <g class="avatar-prop avatar-prop--surprised-spark3" opacity="0">
              <path d="M 0 -7.199999999999999 Q 1.2959999999999998 -1.2959999999999998 7.199999999999999 0 Q 1.2959999999999998 1.2959999999999998 0 7.199999999999999 Q -1.2959999999999998 1.2959999999999998 -7.199999999999999 0 Q -1.2959999999999998 -1.2959999999999998 0 -7.199999999999999 Z" fill="#fbd97a" />
            </g>
          </g>
          <g transform="translate(64.8 -76.0)">
            <g class="avatar-prop avatar-prop--sleepy-z1" opacity="0">
              <path d="M -10.4 -10.4 H 10.4 L -10.4 10.4 H 10.4" fill="none" stroke="#8b95ab" stroke-width="4.99" stroke-linecap="round" stroke-linejoin="round" />
            </g>
          </g>
          <g transform="translate(81.0 -94.4)">
            <g class="avatar-prop avatar-prop--sleepy-z2" opacity="0">
              <path d="M -13.600000000000001 -13.600000000000001 H 13.600000000000001 L -13.600000000000001 13.600000000000001 H 13.600000000000001" fill="none" stroke="#8b95ab" stroke-width="6.53" stroke-linecap="round" stroke-linejoin="round" />
            </g>
          </g>
          <g transform="translate(100.8 -116.0)">
            <g class="avatar-prop avatar-prop--sleepy-z3" opacity="0">
              <path d="M -16.8 -16.8 H 16.8 L -16.8 16.8 H 16.8" fill="none" stroke="#8b95ab" stroke-width="8.06" stroke-linecap="round" stroke-linejoin="round" />
            </g>
          </g>
        </g>
      </g>
    </g>
  </svg>
</template>

<style scoped>
.avatar {
  height: auto;
  display: block;
  overflow: visible;
}

.avatar .avatar-root,
.avatar .avatar-squash,
.avatar .avatar-eye-anim,
.avatar .avatar-eye-blink,
.avatar .avatar-eye-open,
.avatar .avatar-eye-closed,
.avatar .avatar-eye-smile,
.avatar .avatar-eyebrow,
.avatar .avatar-pupil-anim,
.avatar .avatar-pupil,
.avatar .avatar-mouth-anim,
.avatar .avatar-mouth,
.avatar .avatar-prop {
  transform-box: fill-box;
  transform-origin: center;
}

.avatar .avatar-mouth {
  transition: d 0.25s ease;
}

@keyframes avatar-blink {
  0%, 6.8%, 9%, 34.8%, 37%, 76.8%, 79%, 100% { transform: scale(1, 1); }
  7.9%, 35.9%, 77.9% { transform: scale(1, 0.08); }
}

.avatar .avatar-eye-blink {
  animation: avatar-blink 11s linear infinite;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-drift {
  0%, 100% { transform: translate(0px, 0px); }
  30% { transform: translate(1.1px, 0.5px); }
  65% { transform: translate(-1px, 0.3px); }
}

.avatar .avatar-pupil {
  animation: avatar-drift 9s ease-in-out infinite;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

.avatar.avatar-expr--idle {
  --avatar-intensity: 1;
}

@keyframes avatar-idle-squash {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  50% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.006 * var(--avatar-intensity, 1)), calc(1 + 0.015 * var(--avatar-intensity, 1))); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--idle .avatar-squash {
  animation: avatar-idle-squash 3.6s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-idle-eyes {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  56% { transform: translate(0px, calc(-0.8px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--idle .avatar-eye-anim {
  animation: avatar-idle-eyes 3.6s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

.avatar.avatar-expr--happy {
  --avatar-intensity: 1;
}

@keyframes avatar-happy-squash {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  12% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.09 * var(--avatar-intensity, 1)), calc(1 + -0.12 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  36% { transform: translate(0px, calc(-24px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + -0.06 * var(--avatar-intensity, 1)), calc(1 + 0.09 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.5, 0, 0.9, 0.6); }
  58% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.09 * var(--avatar-intensity, 1)), calc(1 + -0.12 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  74% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.015 * var(--avatar-intensity, 1)), calc(1 + 0.03 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--happy .avatar-squash {
  animation: avatar-happy-squash 1.15s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-happy-eyes {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  28% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  44% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.38 * var(--avatar-intensity, 1))); }
  66% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.38 * var(--avatar-intensity, 1))); }
  84% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--happy .avatar-eye-anim {
  animation: avatar-happy-eyes 1.15s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-happy-mouth {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  20% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  42% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.18 * var(--avatar-intensity, 1)), calc(1 + 0.12 * var(--avatar-intensity, 1))); }
  68% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.18 * var(--avatar-intensity, 1)), calc(1 + 0.12 * var(--avatar-intensity, 1))); }
  88% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--happy .avatar-mouth-anim {
  animation: avatar-happy-mouth 1.15s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-happy-mouthd {
  0% { d: path("M -22 0 Q 0 16.8 22 0"); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  40% { d: path("M -22 0 Q 0 28 22 0"); }
  68% { d: path("M -22 0 Q 0 28 22 0"); }
  100% { d: path("M -22 0 Q 0 16.8 22 0"); }
}

.avatar.avatar-expr--happy .avatar-mouth {
  animation: avatar-happy-mouthd 1.15s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

.avatar.avatar-expr--curious {
  --avatar-intensity: 1;
}

@keyframes avatar-curious-root {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  8% { transform: translate(calc(-0.54px * var(--avatar-intensity, 1)), 0px) rotate(calc(-1.5deg * var(--avatar-intensity, 1))) scale(1, 1); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  24% { transform: translate(calc(2.7px * var(--avatar-intensity, 1)), 0px) rotate(calc(8deg * var(--avatar-intensity, 1))) scale(1, 1); }
  72% { transform: translate(calc(2.7px * var(--avatar-intensity, 1)), 0px) rotate(calc(8deg * var(--avatar-intensity, 1))) scale(1, 1); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  90% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-root {
  animation: avatar-curious-root 2.8s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-curious-eyeL {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  24% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  36% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.28 * var(--avatar-intensity, 1)), calc(1 + 0.28 * var(--avatar-intensity, 1))); }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.28 * var(--avatar-intensity, 1)), calc(1 + 0.28 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  86% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-eye--left .avatar-eye-anim {
  animation: avatar-curious-eyeL 2.8s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-eyeR {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  24% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  36% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.14 * var(--avatar-intensity, 1)), calc(1 + -0.14 * var(--avatar-intensity, 1))); }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.14 * var(--avatar-intensity, 1)), calc(1 + -0.14 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  86% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-eye--right .avatar-eye-anim {
  animation: avatar-curious-eyeR 2.8s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-pupils {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  26% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  38% { transform: translate(calc(2.88px * var(--avatar-intensity, 1)), 0px) rotate(0deg) scale(1, 1); }
  70% { transform: translate(calc(2.88px * var(--avatar-intensity, 1)), 0px) rotate(0deg) scale(1, 1); }
  86% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-pupil-anim {
  animation: avatar-curious-pupils 2.8s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-mouth {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  24% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  36% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.28 * var(--avatar-intensity, 1)), calc(1 + -0.15 * var(--avatar-intensity, 1))); }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.28 * var(--avatar-intensity, 1)), calc(1 + -0.15 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  86% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-mouth-anim {
  animation: avatar-curious-mouth 2.8s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-mouthd {
  0% { d: path("M -22 0 Q 0 4.2 22 0"); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  36% { d: path("M -22 0 Q 0 0 22 0"); }
  70% { d: path("M -22 0 Q 0 0 22 0"); }
  100% { d: path("M -22 0 Q 0 4.2 22 0"); }
}

.avatar.avatar-expr--curious .avatar-mouth {
  animation: avatar-curious-mouthd 2.8s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

.avatar.avatar-expr--surprised {
  --avatar-intensity: 1;
}

@keyframes avatar-surprised-squash {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  7% { transform: translate(0px, calc(1.28px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.06 * var(--avatar-intensity, 1)), calc(1 + -0.06 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  17% { transform: translate(calc(-2.7px * var(--avatar-intensity, 1)), calc(-14.4px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + -0.08 * var(--avatar-intensity, 1)), calc(1 + 0.12 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  24% { transform: translate(calc(-1.8px * var(--avatar-intensity, 1)), calc(-10.4px * var(--avatar-intensity, 1))) rotate(calc(1.5deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.02 * var(--avatar-intensity, 1)), calc(1 + 0.04 * var(--avatar-intensity, 1))); }
  32% { transform: translate(calc(-1.8px * var(--avatar-intensity, 1)), calc(-10.88px * var(--avatar-intensity, 1))) rotate(calc(-1.2deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.02 * var(--avatar-intensity, 1)), calc(1 + 0.04 * var(--avatar-intensity, 1))); }
  40% { transform: translate(calc(-1.8px * var(--avatar-intensity, 1)), calc(-10.4px * var(--avatar-intensity, 1))) rotate(calc(0.8deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.02 * var(--avatar-intensity, 1)), calc(1 + 0.04 * var(--avatar-intensity, 1))); }
  48% { transform: translate(calc(-1.8px * var(--avatar-intensity, 1)), calc(-10.56px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + -0.02 * var(--avatar-intensity, 1)), calc(1 + 0.04 * var(--avatar-intensity, 1))); }
  74% { transform: translate(calc(-1.8px * var(--avatar-intensity, 1)), calc(-10.56px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + -0.02 * var(--avatar-intensity, 1)), calc(1 + 0.04 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.22, 1, 0.36, 1); }
  92% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--surprised .avatar-squash {
  animation: avatar-surprised-squash 1.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-surprised-eyes {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  8% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.15 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  20% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.42 * var(--avatar-intensity, 1)), calc(1 + 0.42 * var(--avatar-intensity, 1))); }
  76% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.42 * var(--avatar-intensity, 1)), calc(1 + 0.42 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  90% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--surprised .avatar-eye-anim {
  animation: avatar-surprised-eyes 1.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-pupils {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  20% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.28 * var(--avatar-intensity, 1)), calc(1 + -0.28 * var(--avatar-intensity, 1))); }
  76% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.28 * var(--avatar-intensity, 1)), calc(1 + -0.28 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  90% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--surprised .avatar-pupil-anim {
  animation: avatar-surprised-pupils 1.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-mouth {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  9% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.2 * var(--avatar-intensity, 1)), calc(1 + -0.2 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  22% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.28 * var(--avatar-intensity, 1)), calc(1 + 0.7 * var(--avatar-intensity, 1))); }
  76% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.28 * var(--avatar-intensity, 1)), calc(1 + 0.7 * var(--avatar-intensity, 1))); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  90% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--surprised .avatar-mouth-anim {
  animation: avatar-surprised-mouth 1.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-prop-spark1 {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.8 * var(--avatar-intensity, 1)), calc(1 + -0.8 * var(--avatar-intensity, 1))); opacity: 0; }
  16% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.8 * var(--avatar-intensity, 1)), calc(1 + -0.8 * var(--avatar-intensity, 1))); opacity: 0; animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  25% { transform: translate(0px, 0px) rotate(calc(20deg * var(--avatar-intensity, 1))) scale(calc(1 + 0.1 * var(--avatar-intensity, 1)), calc(1 + 0.1 * var(--avatar-intensity, 1))); opacity: calc(1 * var(--avatar-intensity, 1)); }
  50% { transform: translate(0px, 0px) rotate(calc(45deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.15 * var(--avatar-intensity, 1)), calc(1 + -0.15 * var(--avatar-intensity, 1))); opacity: calc(0.75 * var(--avatar-intensity, 1)); }
  72% { transform: translate(0px, 0px) rotate(calc(65deg * var(--avatar-intensity, 1))) scale(1, 1); opacity: calc(0.9 * var(--avatar-intensity, 1)); }
  86% { transform: translate(0px, 0px) rotate(calc(80deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.6 * var(--avatar-intensity, 1)), calc(1 + -0.6 * var(--avatar-intensity, 1))); opacity: 0; }
  100% { transform: translate(0px, 0px) rotate(calc(80deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.6 * var(--avatar-intensity, 1)), calc(1 + -0.6 * var(--avatar-intensity, 1))); opacity: 0; }
}

.avatar.avatar-expr--surprised .avatar-prop--surprised-spark1 {
  animation: avatar-surprised-prop-spark1 1.6s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-prop-spark2 {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.8 * var(--avatar-intensity, 1)), calc(1 + -0.8 * var(--avatar-intensity, 1))); opacity: 0; }
  20% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.8 * var(--avatar-intensity, 1)), calc(1 + -0.8 * var(--avatar-intensity, 1))); opacity: 0; animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  29% { transform: translate(0px, 0px) rotate(calc(-25deg * var(--avatar-intensity, 1))) scale(calc(1 + 0.1 * var(--avatar-intensity, 1)), calc(1 + 0.1 * var(--avatar-intensity, 1))); opacity: calc(1 * calc((var(--avatar-intensity, 1) - 0.25) / 0.75)); }
  54% { transform: translate(0px, 0px) rotate(calc(-50deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.2 * var(--avatar-intensity, 1)), calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: calc(0.7 * calc((var(--avatar-intensity, 1) - 0.25) / 0.75)); }
  74% { transform: translate(0px, 0px) rotate(calc(-70deg * var(--avatar-intensity, 1))) scale(1, 1); opacity: calc(0.85 * calc((var(--avatar-intensity, 1) - 0.25) / 0.75)); }
  88% { transform: translate(0px, 0px) rotate(calc(-85deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.6 * var(--avatar-intensity, 1)), calc(1 + -0.6 * var(--avatar-intensity, 1))); opacity: 0; }
  100% { transform: translate(0px, 0px) rotate(calc(-85deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.6 * var(--avatar-intensity, 1)), calc(1 + -0.6 * var(--avatar-intensity, 1))); opacity: 0; }
}

.avatar.avatar-expr--surprised .avatar-prop--surprised-spark2 {
  animation: avatar-surprised-prop-spark2 1.6s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-prop-spark3 {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.8 * var(--avatar-intensity, 1)), calc(1 + -0.8 * var(--avatar-intensity, 1))); opacity: 0; }
  24% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.8 * var(--avatar-intensity, 1)), calc(1 + -0.8 * var(--avatar-intensity, 1))); opacity: 0; animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  33% { transform: translate(0px, 0px) rotate(calc(30deg * var(--avatar-intensity, 1))) scale(calc(1 + 0.1 * var(--avatar-intensity, 1)), calc(1 + 0.1 * var(--avatar-intensity, 1))); opacity: calc(0.95 * calc((var(--avatar-intensity, 1) - 0.55) / 0.45)); }
  58% { transform: translate(0px, 0px) rotate(calc(55deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.15 * var(--avatar-intensity, 1)), calc(1 + -0.15 * var(--avatar-intensity, 1))); opacity: calc(0.7 * calc((var(--avatar-intensity, 1) - 0.55) / 0.45)); }
  84% { transform: translate(0px, 0px) rotate(calc(75deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.6 * var(--avatar-intensity, 1)), calc(1 + -0.6 * var(--avatar-intensity, 1))); opacity: 0; }
  100% { transform: translate(0px, 0px) rotate(calc(75deg * var(--avatar-intensity, 1))) scale(calc(1 + -0.6 * var(--avatar-intensity, 1)), calc(1 + -0.6 * var(--avatar-intensity, 1))); opacity: 0; }
}

.avatar.avatar-expr--surprised .avatar-prop--surprised-spark3 {
  animation: avatar-surprised-prop-spark3 1.6s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-mouthd {
  0% { d: path("M -22 0 Q 0 -1.4 22 0"); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  22% { d: path("M -22 0 Q 0 -16.8 22 0"); }
  76% { d: path("M -22 0 Q 0 -15.4 22 0"); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  90% { d: path("M -22 0 Q 0 -1.4 22 0"); }
  100% { d: path("M -22 0 Q 0 -1.4 22 0"); }
}

.avatar.avatar-expr--surprised .avatar-mouth {
  animation: avatar-surprised-mouthd 1.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

.avatar.avatar-expr--sleepy {
  --avatar-intensity: 1;
}

.avatar.avatar-expr--sleepy .avatar-eye-blink {
  animation: none;
}

@keyframes avatar-sleepy-root {
  0% { transform: translate(0px, 0px) rotate(calc(-2.5deg * var(--avatar-intensity, 1))) scale(1, 1); }
  50% { transform: translate(0px, 0px) rotate(calc(2.5deg * var(--avatar-intensity, 1))) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(calc(-2.5deg * var(--avatar-intensity, 1))) scale(1, 1); }
}

.avatar.avatar-expr--sleepy .avatar-root {
  animation: avatar-sleepy-root 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-sleepy-squash {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  42% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.01 * var(--avatar-intensity, 1)), calc(1 + 0.03 * var(--avatar-intensity, 1))); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--sleepy .avatar-squash {
  animation: avatar-sleepy-squash 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-sleepy-eyeOpen {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.34 * var(--avatar-intensity, 1))); opacity: 1; }
  14% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.42 * var(--avatar-intensity, 1))); opacity: 1; animation-timing-function: cubic-bezier(0.5, 0, 0.9, 0.6); }
  20% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.86 * var(--avatar-intensity, 1))); opacity: 1; }
  22% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.88 * var(--avatar-intensity, 1))); opacity: 0; }
  28% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.88 * var(--avatar-intensity, 1))); opacity: 0; }
  30% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.84 * var(--avatar-intensity, 1))); opacity: 1; }
  40% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.4 * var(--avatar-intensity, 1))); opacity: 1; }
  48% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.3 * var(--avatar-intensity, 1))); opacity: 1; }
  62% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.42 * var(--avatar-intensity, 1))); opacity: 1; animation-timing-function: cubic-bezier(0.5, 0, 0.9, 0.6); }
  68% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.86 * var(--avatar-intensity, 1))); opacity: 1; }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.88 * var(--avatar-intensity, 1))); opacity: 0; }
  76% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.88 * var(--avatar-intensity, 1))); opacity: 0; }
  78% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.84 * var(--avatar-intensity, 1))); opacity: 1; }
  88% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.4 * var(--avatar-intensity, 1))); opacity: 1; }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.34 * var(--avatar-intensity, 1))); opacity: 1; }
}

.avatar.avatar-expr--sleepy .avatar-eye-open {
  animation: avatar-sleepy-eyeOpen 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 55%;
}

@keyframes avatar-sleepy-eyeClosed {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: 0; }
  20% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: 0; }
  22% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.1 * var(--avatar-intensity, 1))); opacity: 1; }
  27% { transform: translate(0px, calc(0.6px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, calc(1 + 0.05 * var(--avatar-intensity, 1))); opacity: 1; }
  28% { transform: translate(0px, calc(0.6px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, calc(1 + 0.05 * var(--avatar-intensity, 1))); opacity: 1; }
  30% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: 0; }
  68% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: 0; }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.1 * var(--avatar-intensity, 1))); opacity: 1; }
  75% { transform: translate(0px, calc(0.6px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, calc(1 + 0.05 * var(--avatar-intensity, 1))); opacity: 1; }
  76% { transform: translate(0px, calc(0.6px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, calc(1 + 0.05 * var(--avatar-intensity, 1))); opacity: 1; }
  78% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: 0; }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: 0; }
}

.avatar.avatar-expr--sleepy .avatar-eye-closed {
  animation: avatar-sleepy-eyeClosed 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-pupils {
  0% { transform: translate(0px, calc(2.88px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, calc(2.88px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--sleepy .avatar-pupil-anim {
  animation: avatar-sleepy-pupils 5.2s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-mouth {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.3 * var(--avatar-intensity, 1)), calc(1 + -0.2 * var(--avatar-intensity, 1))); }
  42% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.24 * var(--avatar-intensity, 1)), calc(1 + -0.2 * var(--avatar-intensity, 1))); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.3 * var(--avatar-intensity, 1)), calc(1 + -0.2 * var(--avatar-intensity, 1))); }
}

.avatar.avatar-expr--sleepy .avatar-mouth-anim {
  animation: avatar-sleepy-mouth 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-prop-z1 {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.4 * var(--avatar-intensity, 1)), calc(1 + -0.4 * var(--avatar-intensity, 1))); opacity: 0; }
  8% { transform: translate(calc(0.9px * var(--avatar-intensity, 1)), calc(-2.4px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + -0.3 * var(--avatar-intensity, 1)), calc(1 + -0.3 * var(--avatar-intensity, 1))); opacity: calc(0.8 * var(--avatar-intensity, 1)); }
  30% { transform: translate(calc(3.6px * var(--avatar-intensity, 1)), calc(-9.6px * var(--avatar-intensity, 1))) rotate(0deg) scale(1, 1); opacity: calc(0.7 * var(--avatar-intensity, 1)); }
  46% { transform: translate(calc(5.76px * var(--avatar-intensity, 1)), calc(-16px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.1 * var(--avatar-intensity, 1)), calc(1 + 0.1 * var(--avatar-intensity, 1))); opacity: 0; }
  100% { transform: translate(calc(5.76px * var(--avatar-intensity, 1)), calc(-16px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.1 * var(--avatar-intensity, 1)), calc(1 + 0.1 * var(--avatar-intensity, 1))); opacity: 0; }
}

.avatar.avatar-expr--sleepy .avatar-prop--sleepy-z1 {
  animation: avatar-sleepy-prop-z1 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-prop-z2 {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.4 * var(--avatar-intensity, 1)), calc(1 + -0.4 * var(--avatar-intensity, 1))); opacity: 0; }
  28% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.4 * var(--avatar-intensity, 1)), calc(1 + -0.4 * var(--avatar-intensity, 1))); opacity: 0; }
  38% { transform: translate(calc(1.08px * var(--avatar-intensity, 1)), calc(-2.88px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + -0.25 * var(--avatar-intensity, 1)), calc(1 + -0.25 * var(--avatar-intensity, 1))); opacity: calc(0.8 * calc((var(--avatar-intensity, 1) - 0.3) / 0.7)); }
  60% { transform: translate(calc(4.32px * var(--avatar-intensity, 1)), calc(-10.4px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.05 * var(--avatar-intensity, 1)), calc(1 + 0.05 * var(--avatar-intensity, 1))); opacity: calc(0.65 * calc((var(--avatar-intensity, 1) - 0.3) / 0.7)); }
  76% { transform: translate(calc(6.48px * var(--avatar-intensity, 1)), calc(-16.8px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.15 * var(--avatar-intensity, 1)), calc(1 + 0.15 * var(--avatar-intensity, 1))); opacity: 0; }
  100% { transform: translate(calc(6.48px * var(--avatar-intensity, 1)), calc(-16.8px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.15 * var(--avatar-intensity, 1)), calc(1 + 0.15 * var(--avatar-intensity, 1))); opacity: 0; }
}

.avatar.avatar-expr--sleepy .avatar-prop--sleepy-z2 {
  animation: avatar-sleepy-prop-z2 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-prop-z3 {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.4 * var(--avatar-intensity, 1)), calc(1 + -0.4 * var(--avatar-intensity, 1))); opacity: 0; }
  52% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.4 * var(--avatar-intensity, 1)), calc(1 + -0.4 * var(--avatar-intensity, 1))); opacity: 0; }
  62% { transform: translate(calc(1.26px * var(--avatar-intensity, 1)), calc(-3.2px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + -0.2 * var(--avatar-intensity, 1)), calc(1 + -0.2 * var(--avatar-intensity, 1))); opacity: calc(0.75 * calc((var(--avatar-intensity, 1) - 0.65) / 0.35)); }
  82% { transform: translate(calc(4.68px * var(--avatar-intensity, 1)), calc(-11.2px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.1 * var(--avatar-intensity, 1)), calc(1 + 0.1 * var(--avatar-intensity, 1))); opacity: calc(0.55 * calc((var(--avatar-intensity, 1) - 0.65) / 0.35)); }
  96% { transform: translate(calc(6.84px * var(--avatar-intensity, 1)), calc(-17.6px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.2 * var(--avatar-intensity, 1)), calc(1 + 0.2 * var(--avatar-intensity, 1))); opacity: 0; }
  100% { transform: translate(calc(6.84px * var(--avatar-intensity, 1)), calc(-17.6px * var(--avatar-intensity, 1))) rotate(0deg) scale(calc(1 + 0.2 * var(--avatar-intensity, 1)), calc(1 + 0.2 * var(--avatar-intensity, 1))); opacity: 0; }
}

.avatar.avatar-expr--sleepy .avatar-prop--sleepy-z3 {
  animation: avatar-sleepy-prop-z3 5.2s cubic-bezier(0.45, 0, 0.55, 1) infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-mouthd {
  0% { d: path("M -22 0 Q 0 0 22 0"); }
  100% { d: path("M -22 0 Q 0 0 22 0"); }
}

.avatar.avatar-expr--sleepy .avatar-mouth {
  animation: avatar-sleepy-mouthd 5.2s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

.avatar.avatar-expr--wink {
  --avatar-intensity: 1;
}

.avatar.avatar-expr--wink .avatar-eye-blink {
  animation: none;
}

@keyframes avatar-wink-eyeROpen {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); opacity: 1; }
  12% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + 0.08 * var(--avatar-intensity, 1))); opacity: 1; animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  19% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.85 * var(--avatar-intensity, 1))); opacity: 1; }
  21% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.88 * var(--avatar-intensity, 1))); opacity: 0; }
  60% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.88 * var(--avatar-intensity, 1))); opacity: 0; }
  62% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.84 * var(--avatar-intensity, 1))); opacity: 1; animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  72% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + 0.08 * var(--avatar-intensity, 1))); opacity: 1; }
  84% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); opacity: 1; }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); opacity: 1; }
}

.avatar.avatar-expr--wink .avatar-eye--right .avatar-eye-open {
  animation: avatar-wink-eyeROpen 1.3s cubic-bezier(0.45, 0, 0.55, 1) 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 55%;
}

@keyframes avatar-wink-eyeRClosed {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.05 * var(--avatar-intensity, 1)), 1); opacity: 0; }
  19% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.05 * var(--avatar-intensity, 1)), 1); opacity: 0; animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  21% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.08 * var(--avatar-intensity, 1)), 1); opacity: 1; }
  60% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + 0.08 * var(--avatar-intensity, 1)), 1); opacity: 1; }
  62% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.05 * var(--avatar-intensity, 1)), 1); opacity: 0; }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(calc(1 + -0.05 * var(--avatar-intensity, 1)), 1); opacity: 0; }
}

.avatar.avatar-expr--wink .avatar-eye--right .avatar-eye-closed {
  animation: avatar-wink-eyeRClosed 1.3s cubic-bezier(0.45, 0, 0.55, 1) 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-wink-eyeL {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  16% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.08 * var(--avatar-intensity, 1))); }
  58% { transform: translate(0px, 0px) rotate(0deg) scale(1, calc(1 + -0.08 * var(--avatar-intensity, 1))); }
  72% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--wink .avatar-eye--left .avatar-eye-anim {
  animation: avatar-wink-eyeL 1.3s cubic-bezier(0.45, 0, 0.55, 1) 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-wink-root {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.55, 0, 0.7, 0.3); }
  10% { transform: translate(calc(-0.36px * var(--avatar-intensity, 1)), 0px) rotate(calc(-1.2deg * var(--avatar-intensity, 1))) scale(1, 1); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  22% { transform: translate(calc(1.44px * var(--avatar-intensity, 1)), 0px) rotate(calc(4deg * var(--avatar-intensity, 1))) scale(1, 1); }
  58% { transform: translate(calc(1.44px * var(--avatar-intensity, 1)), 0px) rotate(calc(4deg * var(--avatar-intensity, 1))) scale(1, 1); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  72% { transform: translate(0px, 0px) rotate(calc(-0.5deg * var(--avatar-intensity, 1))) scale(1, 1); }
  84% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--wink .avatar-root {
  animation: avatar-wink-root 1.3s ease-in-out 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-wink-mouth {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  14% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); animation-timing-function: cubic-bezier(0.34, 1.56, 0.64, 1); }
  24% { transform: translate(calc(1.8px * var(--avatar-intensity, 1)), 0px) rotate(calc(-7deg * var(--avatar-intensity, 1))) scale(calc(1 + 0.12 * var(--avatar-intensity, 1)), 1); }
  58% { transform: translate(calc(1.8px * var(--avatar-intensity, 1)), 0px) rotate(calc(-7deg * var(--avatar-intensity, 1))) scale(calc(1 + 0.12 * var(--avatar-intensity, 1)), 1); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  76% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--wink .avatar-mouth-anim {
  animation: avatar-wink-mouth 1.3s cubic-bezier(0.45, 0, 0.55, 1) 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-wink-mouthd {
  0% { d: path("M -22 0 Q 0 16.8 22 0"); animation-timing-function: cubic-bezier(0.45, 0, 0.55, 1); }
  24% { d: path("M -22 0 Q 0 26.6 22 0"); }
  58% { d: path("M -22 0 Q 0 26.6 22 0"); }
  80% { d: path("M -22 0 Q 0 16.8 22 0"); }
  100% { d: path("M -22 0 Q 0 16.8 22 0"); }
}

.avatar.avatar-expr--wink .avatar-mouth {
  animation: avatar-wink-mouthd 1.3s ease-in-out 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}
</style>

<!-- Play-once expressions (wink) emit "animation-end" when they finish. -->
