<script setup>
// BoxBuddy.vue — generated by Avatar Builder. No runtime dependencies.
import { computed, ref, watch } from 'vue'

const props = defineProps({
  /** One of: idle, happy, curious, surprised, sleepy, wink */
  expression: {
    type: String,
    default: 'idle',
    validator: (value) => ["idle","happy","curious","surprised","sleepy","wink"].includes(value),
  },
  /** Rendered width — a number of pixels or any CSS size. */
  size: {
    type: [Number, String],
    default: 200,
  },
  paused: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits(['animation-end'])

const cssSize = computed(() => (typeof props.size === 'number' ? `${props.size}px` : props.size))

const hasEmittedEnd = ref(false)
watch(() => props.expression, () => {
  hasEmittedEnd.value = false
})

function onAnimationEnd(event) {
  // Several tracks finish together; report the expression once per play.
  if (hasEmittedEnd.value) return
  if (!event.animationName.includes(`avatar-${props.expression}-`)) return
  hasEmittedEnd.value = true
  emit('animation-end', props.expression)
}
</script>

<template>
  <svg
    class="avatar"
    :class="`avatar-expr--${expression}`"
    :style="{ width: cssSize, '--avatar-play': paused ? 'paused' : 'running' }"
    viewBox="-114.3 -176.3 228.5 280.3"
    xmlns="http://www.w3.org/2000/svg"
    role="img"
    aria-label="BoxBuddy avatar"
    @animationend="onAnimationEnd"
  >
    <defs>
      <linearGradient id="avatar-body-grad" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stop-color="#d9a066" />
        <stop offset="100%" stop-color="#b28354" />
      </linearGradient>
      <clipPath id="avatar-eye-clip">
        <path d="M -16 0 a 16 16 0 1 0 32 0 a 16 16 0 1 0 -32 0 Z" />
      </clipPath>
    </defs>
    <g class="avatar-root">
      <g class="avatar-squash">
        <g class="avatar-body">
          <path d="M -66 -80 h 132 a 24 24 0 0 1 24 24 v 112 a 24 24 0 0 1 -24 24 h -132 a 24 24 0 0 1 -24 -24 v -112 a 24 24 0 0 1 24 -24 Z" fill="url(#avatar-body-grad)" />
        </g>
        <g class="avatar-face">
          <g class="avatar-eye avatar-eye--left" transform="translate(-38 -18)">
            <g class="avatar-eye-anim">
              <g class="avatar-eye-blink">
                <g transform="scale(1 1)">
                  <path d="M -16 0 a 16 16 0 1 0 32 0 a 16 16 0 1 0 -32 0 Z" fill="#ffffff" />
                  <g clip-path="url(#avatar-eye-clip)">
                    <g class="avatar-pupil-anim">
                      <g class="avatar-pupil">
                        <circle r="7.2" cy="1.6" fill="#2b2b2b" />
                        <circle r="2.3" cx="-2.52" cy="-0.92" fill="#ffffff" opacity="0.9" />
                      </g>
                    </g>
                  </g>
                </g>
              </g>
            </g>
          </g>
          <g class="avatar-eye avatar-eye--right" transform="translate(38 -18)">
            <g class="avatar-eye-anim">
              <g class="avatar-eye-blink">
                <g transform="scale(1 1)">
                  <path d="M -16 0 a 16 16 0 1 0 32 0 a 16 16 0 1 0 -32 0 Z" fill="#ffffff" />
                  <g clip-path="url(#avatar-eye-clip)">
                    <g class="avatar-pupil-anim">
                      <g class="avatar-pupil">
                        <circle r="7.2" cy="1.6" fill="#2b2b2b" />
                        <circle r="2.3" cx="-2.52" cy="-0.92" fill="#ffffff" opacity="0.9" />
                      </g>
                    </g>
                  </g>
                </g>
              </g>
            </g>
          </g>
          <g class="avatar-mouth-wrap" transform="translate(0 28)">
            <g class="avatar-mouth-anim">
              <path class="avatar-mouth" d="M -22 0 Q 0 25.2 22 0" fill="none" stroke="#2b2b2b" stroke-width="4.5" stroke-linecap="round" />
            </g>
          </g>
        </g>
        <g class="avatar-part" data-part-id="tape" transform="translate(0 -62)">
          <path d="M -86.5 -7 h 173 a 3.5 3.5 0 0 1 3.5 3.5 v 7 a 3.5 3.5 0 0 1 -3.5 3.5 h -173 a 3.5 3.5 0 0 1 -3.5 -3.5 v -7 a 3.5 3.5 0 0 1 3.5 -3.5 Z" fill="#c98d52" />
        </g>
        <g class="avatar-part" data-part-id="label" transform="translate(52 52) rotate(-6)">
          <path d="M -18 -14 h 36 a 4 4 0 0 1 4 4 v 20 a 4 4 0 0 1 -4 4 h -36 a 4 4 0 0 1 -4 -4 v -20 a 4 4 0 0 1 4 -4 Z" fill="#f2e6d4" stroke="#b07d4a" stroke-width="2" />
        </g>
        <g class="avatar-part" data-part-id="blush" transform="translate(-52 8)">
          <path d="M -11 0 a 11 6 0 1 0 22 0 a 11 6 0 1 0 -22 0 Z" fill="#e8917c" opacity="0.65" />
        </g>
        <g class="avatar-part" data-part-id="blush--mirror" transform="translate(52 8) scale(-1 1)">
          <path d="M -11 0 a 11 6 0 1 0 22 0 a 11 6 0 1 0 -22 0 Z" fill="#e8917c" opacity="0.65" />
        </g>
      </g>
    </g>
  </svg>
</template>

<style scoped>
.avatar {
  height: auto;
  display: block;
  overflow: visible;
}

.avatar .avatar-root,
.avatar .avatar-squash,
.avatar .avatar-eye-anim,
.avatar .avatar-eye-blink,
.avatar .avatar-pupil-anim,
.avatar .avatar-pupil,
.avatar .avatar-mouth-anim,
.avatar .avatar-mouth {
  transform-box: fill-box;
  transform-origin: center;
}

.avatar .avatar-mouth {
  transition: d 0.25s ease;
}

@keyframes avatar-blink {
  0%, 6.8%, 9%, 34.8%, 37%, 76.8%, 79%, 100% { transform: scale(1, 1); }
  7.9%, 35.9%, 77.9% { transform: scale(1, 0.08); }
}

.avatar .avatar-eye-blink {
  animation: avatar-blink 11s linear infinite;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-drift {
  0%, 100% { transform: translate(0px, 0px); }
  30% { transform: translate(1.6px, 0.8px); }
  65% { transform: translate(-1.4px, 0.5px); }
}

.avatar .avatar-pupil {
  animation: avatar-drift 9s ease-in-out infinite;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-happy-squash {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  25% { transform: translate(0px, 0px) rotate(0deg) scale(1.06, 0.9); }
  55% { transform: translate(0px, -14px) rotate(0deg) scale(0.97, 1.06); }
  80% { transform: translate(0px, 0px) rotate(0deg) scale(1.03, 0.96); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--happy .avatar-squash {
  animation: avatar-happy-squash 1.1s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-happy-eyes {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  55% { transform: translate(0px, 0px) rotate(0deg) scale(1, 0.85); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--happy .avatar-eye-anim {
  animation: avatar-happy-eyes 1.1s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-happy-mouthd {
  0% { d: path("M -22 0 Q 0 36 22 0"); }
  100% { d: path("M -22 0 Q 0 36 22 0"); }
}

.avatar.avatar-expr--happy .avatar-mouth {
  animation: avatar-happy-mouthd 1.1s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-root {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  30% { transform: translate(0px, 0px) rotate(8deg) scale(1, 1); }
  70% { transform: translate(0px, 0px) rotate(8deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-root {
  animation: avatar-curious-root 2.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-eyeL {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  30% { transform: translate(0px, 0px) rotate(0deg) scale(1.22, 1.22); }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(1.22, 1.22); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-eye--left .avatar-eye-anim {
  animation: avatar-curious-eyeL 2.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-eyeR {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  30% { transform: translate(0px, 0px) rotate(0deg) scale(0.85, 0.85); }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(0.85, 0.85); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-eye--right .avatar-eye-anim {
  animation: avatar-curious-eyeR 2.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-pupils {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  30% { transform: translate(2.5px, 0px) rotate(0deg) scale(1, 1); }
  70% { transform: translate(2.5px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--curious .avatar-pupil-anim {
  animation: avatar-curious-pupils 2.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-curious-mouthd {
  0% { d: path("M -22 0 Q 0 7.2 22 0"); }
  100% { d: path("M -22 0 Q 0 7.2 22 0"); }
}

.avatar.avatar-expr--curious .avatar-mouth {
  animation: avatar-curious-mouthd 2.6s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-squash {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  15% { transform: translate(0px, 0px) rotate(0deg) scale(0.95, 1.08); }
  40% { transform: translate(0px, 0px) rotate(0deg) scale(0.97, 1.05); }
  70% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--surprised .avatar-squash {
  animation: avatar-surprised-squash 1.4s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
  transform-origin: 50% 100%;
}

@keyframes avatar-surprised-eyes {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  15% { transform: translate(0px, 0px) rotate(0deg) scale(1.35, 1.35); }
  55% { transform: translate(0px, 0px) rotate(0deg) scale(1.3, 1.3); }
  90% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--surprised .avatar-eye-anim {
  animation: avatar-surprised-eyes 1.4s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-mouth {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  15% { transform: translate(0px, 0px) rotate(0deg) scale(1.35, 1.5); }
  55% { transform: translate(0px, 0px) rotate(0deg) scale(1.3, 1.45); }
  90% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--surprised .avatar-mouth-anim {
  animation: avatar-surprised-mouth 1.4s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-surprised-mouthd {
  0% { d: path("M -22 0 Q 0 -7.2 22 0"); }
  100% { d: path("M -22 0 Q 0 -7.2 22 0"); }
}

.avatar.avatar-expr--surprised .avatar-mouth {
  animation: avatar-surprised-mouthd 1.4s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-root {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  50% { transform: translate(0px, 3px) rotate(2.5deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--sleepy .avatar-root {
  animation: avatar-sleepy-root 4.2s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-eyes {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 0.38); }
  50% { transform: translate(0px, 0px) rotate(0deg) scale(1, 0.28); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 0.38); }
}

.avatar.avatar-expr--sleepy .avatar-eye-anim {
  animation: avatar-sleepy-eyes 4.2s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-pupils {
  0% { transform: translate(0px, 2px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 2px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--sleepy .avatar-pupil-anim {
  animation: avatar-sleepy-pupils 4.2s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-sleepy-mouthd {
  0% { d: path("M -22 0 Q 0 5.4 22 0"); }
  100% { d: path("M -22 0 Q 0 5.4 22 0"); }
}

.avatar.avatar-expr--sleepy .avatar-mouth {
  animation: avatar-sleepy-mouthd 4.2s ease-in-out infinite both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-wink-eyeR {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  18% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  28% { transform: translate(0px, 0px) rotate(0deg) scale(1, 0.08); }
  50% { transform: translate(0px, 0px) rotate(0deg) scale(1, 0.08); }
  62% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--wink .avatar-eye--right .avatar-eye-anim {
  animation: avatar-wink-eyeR 1.8s ease-in-out 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-wink-root {
  0% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  28% { transform: translate(0px, 0px) rotate(3deg) scale(1, 1); }
  50% { transform: translate(0px, 0px) rotate(3deg) scale(1, 1); }
  62% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
  100% { transform: translate(0px, 0px) rotate(0deg) scale(1, 1); }
}

.avatar.avatar-expr--wink .avatar-root {
  animation: avatar-wink-root 1.8s ease-in-out 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}

@keyframes avatar-wink-mouthd {
  0% { d: path("M -22 0 Q 0 32.4 22 0"); }
  100% { d: path("M -22 0 Q 0 32.4 22 0"); }
}

.avatar.avatar-expr--wink .avatar-mouth {
  animation: avatar-wink-mouthd 1.8s ease-in-out 1 both;
  animation-play-state: var(--avatar-play, running);
  animation-delay: var(--avatar-seek, 0s);
}
</style>

<!-- Play-once expressions (wink) emit "animation-end" when they finish. -->
